config/routes.rb
Rails.application.routes.draw do
  resources :frindes
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frinde.rb
class Frinde < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frindes_controller.rb
class FrindesController < ApplicationController
  before_action :set_frinde, only: %i[ show edit update destroy ]

  # GET /frindes or /frindes.json
  def index
    @frindes = Frinde.all
  end

  # GET /frindes/1 or /frindes/1.json
  def show
  end

  # GET /frindes/new
  def new
    @frinde = Frinde.new
  end

  # GET /frindes/1/edit
  def edit
  end

  # POST /frindes or /frindes.json
  def create
    @frinde = Frinde.new(frinde_params)

    respond_to do |format|
      if @frinde.save
        format.html { redirect_to @frinde, notice: "Frinde was successfully created." }
        format.json { render :show, status: :created, location: @frinde }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frinde.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frindes/1 or /frindes/1.json
  def update
    respond_to do |format|
      if @frinde.update(frinde_params)
        format.html { redirect_to @frinde, notice: "Frinde was successfully updated." }
        format.json { render :show, status: :ok, location: @frinde }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frinde.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frindes/1 or /frindes/1.json
  def destroy
    @frinde.destroy
    respond_to do |format|
      format.html { redirect_to frindes_url, notice: "Frinde was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frinde
      @frinde = Frinde.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frinde_params
      params.require(:frinde).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frindes_helper.rb
module FrindesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frindes/_form.html.erb
<%= form_with(model: frinde) do |form| %>
<% if frinde.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(frinde.errors.count, "error") %> prohibited this frinde from being saved:</h2>

    <ul>
        <% frinde.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field form-group mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
</div>

<div class="field form-group mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
</div>

<div class="field form-group mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
</div>

<div class="field form-group mb-3">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
</div>

<div class="field form-group mb-3">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control" %>
</div>

<div class="actions">
    <%= form.submit class:"btn btn-dark" %>
</div>
<% end %>

app/views/frindes/edit.html.erb
<h1>Editing Frinde</h1>

<%= render 'form', frinde: @frinde %>

<%= link_to 'Show', @frinde %> |
<%= link_to 'Back', frindes_path %>

app/views/frindes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends List</h1>

<table class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Twitter</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @frindes.each do |frinde| %>
        <tr>
            <td><%= frinde.first_name %></td>
            <td><%= frinde.last_name %></td>
            <td><%= frinde.email %></td>
            <td><%= frinde.phone %></td>
            <td><%= frinde.twitter %></td>
            <td><%= link_to 'Show', frinde %></td>
            <td><%= link_to 'Edit', edit_frinde_path(frinde) %></td>
            <td><%= link_to 'Destroy', frinde, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Frinde', new_frinde_path, class: "btn btn-secondary" %>

app/views/frindes/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', frinde: @frinde %>

<%= link_to 'Back', frindes_path %>

app/views/frindes/show.html.erb
<div class="jumbotron">
    <h1 class="display-4"><%= @frinde.first_name %> <%= @frinde.last_name %></h1>
    <p class="lead"> <%= @frinde.email %> | <%= @frinde.phone %> | <%= @frinde.twitter %> </p>
    <hr class="my-4" />
    <%= link_to 'Edit', edit_frinde_path(@frinde), class: "btn btn-secondary" %>
    <%= link_to 'Back', frindes_path, class: "btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Frineds App", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Friends", frindes_path, class: 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to "Add Friend", new_frinde_path, class: 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to "About US", home_about_path, class: 'nav-link' %>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<h1> Hello World! </h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Frineds App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
    <%= render 'home/header' %>
    <div class="container">
        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
</body>

</html>